In [1]:
import numpy as np

In [2]:
# Define a list of sentences as our corpus
corpus = ['this is a a sample', 'this is another another example example example']

In [3]:
# Create a set of unique words from the corpus by iterating over each sentence and each word in the sentence
vocabs = list(set([word for doc in corpus for word in doc.split()]))
vocabs

['is', 'a', 'another', 'this', 'example', 'sample']

In [4]:
# Create a dictionary mapping each unique word to an integer index
word2id = {w:i for i, w in enumerate(vocabs)}

In [5]:
# Tokenize the sentences in the corpus by replacing each word in the sentence with its corresponding integer index
corpus = [[word2id[word] for word in doc.split()] for doc in corpus]

In [6]:
corpus

[[3, 0, 1, 1, 5], [3, 0, 2, 2, 4, 4, 4]]

# Definition TF-IDF
1. The tf–idf is the product of two statistics, term frequency and inverse document frequency. There are various ways for determining the exact values of both statistics.
2. A formula that aims to define the importance of a keyword or phrase within a document or a web page.

In [7]:
doc_size = len(corpus)
vocab_size = len(vocabs)
counts = np.zeros((doc_size, vocab_size)) # when using ndarray it return the same address and the previous values
counts

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
for i in range(doc_size):
    for word in corpus[i]:
        counts[i][word] += 1

In [9]:
counts

array([[1., 2., 0., 1., 0., 1.],
       [1., 0., 2., 1., 3., 0.]])

## Term frequency
Term frequency, tf(t,d), is the relative frequency of term t within document d,
$$
{\displaystyle \mathrm {tf} (t,d)={\frac {f_{t,d}}{\sum _{t'\in d}{f_{t',d}}}}},
$$
where $f_{t,d}$ is the raw count of a term in a document, i.e., the number of times that term $t$ occurs in document $d$. Note the denominator is simply the total number of terms in document $d$ (counting each occurrence of the same term separately). 

In [10]:
tf = np.zeros_like(counts)
for i in range(doc_size): # O(nxm)
    wc_sum = 0
    for wc in counts[i]: wc_sum += wc # O(m)
    for j in range(vocab_size): # word count in doc O(m)
        tf[i][j] = counts[i][j]/wc_sum
tf

array([[0.2       , 0.4       , 0.        , 0.2       , 0.        ,
        0.2       ],
       [0.14285714, 0.        , 0.28571429, 0.14285714, 0.42857143,
        0.        ]])

## The inverse document frequency
The inverse document frequency is a measure of how much information the word provides, i.e., if it is common or rare across all documents. It is the logarithmically scaled inverse fraction of the documents that contain the word (obtained by dividing the total number of documents by the number of documents containing the term, and then taking the logarithm of that quotient):

$$
\mathrm{idf}(t, D) =  \log \frac{N}{|\{d \in D: t \in d\}|}
$$

with

- N: total number of documents in the corpus $N = {|D|}$

- $|\{d \in D: t \in d\}|$  : number of documents where the term $mathrm{tf}(t,d) \neq 0)$. If the term is not in the corpus, this will lead to a division-by-zero. It is therefore common to adjust the denominator to $1 + |\{d \in D: t \in d\}|.$

In [11]:
idf = np.zeros(vocab_size)
for i in range(vocab_size):
    w_dc = 1 # word found in `w_dc` docs, start with 1 to prevent division-by-zero
    for j in range(doc_size):
        if counts[j][i] != 0: w_dc += 1
    idf[i] = np.log10(doc_size/w_dc)
idf

array([-0.17609126,  0.        ,  0.        , -0.17609126,  0.        ,
        0.        ])

In [12]:
tf*idf

array([[-0.03521825,  0.        ,  0.        , -0.03521825,  0.        ,
         0.        ],
       [-0.02515589,  0.        ,  0.        , -0.02515589,  0.        ,
         0.        ]])